package go_exglobal

type ExGlobalBankCode struct {
	Currency       string `json:"currency"`
	ClientBankCode string `json:"clientBankCode"`
	Code           string `json:"code"`
	Name           string `json:"name"`
	Channel        string `json:"channel"`
}

var DepositBankCodes = []ExGlobalBankCode{}

var WithdrawBankCodes = []ExGlobalBankCode{
	{"VND", "WooriBank", "WOORIBANK", "Woori - NGAN HANG TNHH MTV WOORI BANK TAI VIET NAM (WOORI)", "BankDirect"},
	{"VND", "VTB", "VTB", "VietinBank - NGAN HANG TMCP CONG THUONG VIET NAM (VIETINBANK)", "BankDirect"},
	{"VND", "VietinBank", "VTB", "VietinBank - NGAN HANG TMCP CONG THUONG VIET NAM (VIETINBANK)", "BankDirect"},
	{"VND", "", "VRB", "VRB - NGAN HANG LIEN DOANH VIET - NGA (VRB)", "BankDirect"},
	{"VND", "VPB", "VPB", "VPBank - NGAN HANG TMCP VIET NAM THINH VUONG (VPBANK)", "BankDirect"},
	{"VND", "VPBank", "VPB", "VPBank - NGAN HANG TMCP VIET NAM THINH VUONG (VPBANK)", "BankDirect"},
	{"VND", "VietCapitalBank", "VIETCAPITALBANK", "VietCapitalBank - NGAN HANG TMCP BAN VIET (VIETCAPITAL)", "BankDirect"},
	{"VND", "Vietbank", "VIETBANK", "VietBank - NGAN HANG TMCP VIET NAM THUONG TIN (VIETBANK)", "BankDirect"},
	{"VND", "VietABank", "VIETABANK", "VietABank - NGAN HANG TMCP VIET A (VIETABANK)", "BankDirect"},
	{"VND", "VIB", "VIB", "VIB - NGAN HANG QUOC TE (VIB)", "BankDirect"},
	{"VND", "VCB", "VCB", "Vietcombank - NGAN HANG TMCP NGOAI THUONG VIET NAM (VCB)", "BankDirect"},
	{"VND", "", "UOB", "UOB - NGAN HANG TNHH MTV UNITED OVERSEAS BANK (UOB)", "BankDirect"},
	{"VND", "TPB", "TPB", "TPBank - NGAN HANG TMCP TIEN PHONG (TPBANK)", "BankDirect"},
	{"VND", "TPBank", "TPB", "TPBank - NGAN HANG TMCP TIEN PHONG (TPBANK)", "BankDirect"},
	{"VND", "TCB", "TCB", "Techcombank - NGAN HANG TMCP KY THUONG VIET NAM (TCB)", "BankDirect"},
	{"VND", "Shinhan", "SHINHANBANK", "Shinhan - NGAN HANG SHINHAN VIET NAM (SHINHAN)", "BankDirect"},
	{"VND", "SHB", "SHB", "SHB - NGAN HANG TMCP SAI GON - HA NOI (SHB)", "BankDirect"},
	{"VND", "SeABank", "SEABANK", "SeaBank - NGAN HANG TMCP DONG NAM A (SEABANK)", "BankDirect"},
	{"VND", "SCB", "SCB", "SCB - NGAN HANG TMCP SAI GON (SCB)", "BankDirect"},
	{"VND", "", "SAIGONBANK", "SaigonBank - NGAN HANG TMCP SAI GON CONG THUONG (SAIGONBANK)", "BankDirect"},
	{"VND", "SACOM", "SACOMBANK", "Sacombank - NGAN HANG TMCP SAI GON THUONG TIN (SACOMBANK)", "BankDirect"},
	{"VND", "Sacombank", "SACOMBANK", "Sacombank - NGAN HANG TMCP SAI GON THUONG TIN (SACOMBANK)", "BankDirect"},
	{"VND", "Pvcombank", "PVCOMBANK", "PVComBank - NGAN HANG TMCP DAI CHUNG VIET NAM (PVCOMBANK)", "BankDirect"},
	{"VND", "PGBank", "PGBANK", "PGBank - NGAN HANG TMCP XANG DAU PETROLIMEX (PGBANK)", "BankDirect"},
	{"VND", "PBVN", "PBVN", "PBVN - NGAN HANG PUBLIC BANK VIET NAM (PBVN)", "BankDirect"},
	{"VND", "Oceanbank", "OJB", "OceanBank - NGAN HANG TMCP DAI DUONG (OCEANBANK)", "BankDirect"},
	{"VND", "OCB", "OCB", "OCB - NGAN HANG TMCP PHUONG DONG (OCB)", "BankDirect"},
	{"VND", "NCB", "NCB", "NCB - NGAN HANG TMCP QUOC DAN (NCB)", "BankDirect"},
	{"VND", "NAMABANK", "NAMABANK", "NamABank - NGAN HANG TMCP NAM A (NAMABANK)", "BankDirect"},
	{"VND", "MSB", "MSB", "MaritimeBank - NGAN HANG TMCP HANG HAI VIET NAM (MSB)", "BankDirect"},
	{"VND", "MB", "MB", "MBBank - NGAN HANG TMCP QUAN DOI (MBBANK)", "BankDirect"},
	{"VND", "MBBank", "MB", "MBBank - NGAN HANG TMCP QUAN DOI (MBBANK)", "BankDirect"},
	{"VND", "", "LVPB", "LPB - NGAN HANG BUU DIEN LIEN VIET (LPB)", "BankDirect"},
	{"VND", "Kienlongbank", "KIENLONGBANK", "KienLongBank - NGAN HANG TMCP KIEN LONG (KLB)", "BankDirect"},
	{"VND", "INDOVINA", "IVB", "Indovina - NGAN HANG TNHH INDOVINA (IVB)", "BankDirect"},
	{"VND", "HSBC", "HSBC", "HSBC - NGAN HANG HSBC VIET NAM (HSBC)", "BankDirect"},
	{"VND", "", "HLBANK", "HLBank - NGAN HANG TNHH MTV HONG LEONG VIET NAM (HLBANK)", "BankDirect"},
	{"VND", "HDBank", "HDB", "HDBank - NGAN HANG TMCP PHAT TRIEN TP.HCM (HDBANK)", "BankDirect"},
	{"VND", "", "GPBANK", "GPBank - NGAN HANG TM TNHH MTV DAU KHI TOAN CAU (GPBANK)", "BankDirect"},
	{"VND", "EXIM", "EIB", "Eximbank - NGAN HANG TMCP XUAT NHAP KHAU VIET NAM (EXIMBANK)", "BankDirect"},
	{"VND", "DongABank", "DONGABANK", "DongABank - NGAN HANG TMCP DONG A (DONGABANK)", "BankDirect"},
	{"VND", "", "CIMB", "CIMB - NGAN HANG CIMB VIET NAM (CIMB)", "BankDirect"},
	{"VND", "", "CBB", "CBB - NGAN HANG XAY DUNG VIET NAM (CBB)", "BankDirect"},
	{"VND", "", "CAKE", "Cake - NGAN HANG SO CAKE BY VPBANK (CAKE)", "BankDirect"},
	{"VND", "", "BVB", "BVB - NGAN HANG TMCP BAO VIET (BVB)", "BankDirect"},
	{"VND", "BIDV", "BIDV", "BIDV - NGAN HANG TMCP DAU TU VA PHAT TRIEN VIET NAM (BIDV)", "BankDirect"},
	{"VND", "BacABank", "BACABANK", "BacABank - NGAN HANG TMCP BAC A (BACABANK)", "BankDirect"},
	{"VND", "Agribank", "AGRIBANK", "Agribank - NGAN HANG NONG NGHIEP VA PHAT TRIEN NONG THON VIET NAM (AGRIBANK)", "BankDirect"},
	{"VND", "ACB", "ACB", "ACB - NGAN HANG TMCP A CHAU (ACB)", "BankDirect"},
	{"VND", "ABBank", "ABB", "ABBANK - NGAN HANG TMCP AN BINH (ABBANK)", "BankDirect"},

	{"THB", "UOBT", "UOBT", "ธนาคารยูโอบี จำกัด (มหาชน)(United Overseas Bank (Thai))", "THBBankDirect"},
	{"THB", "TMB", "TMB", "ธนาคารทหารไทย(TMBThanachart Bank Public Company Limited)", "THBBankDirect"},
	{"THB", "TISCO", "TISCO", "ธนาคารทิสโก้ จำกัด (มหาชน)(Tisco Bank)", "THBBankDirect"},
	{"THB", "", "TCRB", "ธนาคารไทยเครดิต เพื่อรายย่อย จำกัด (มหาชน)(Thai Credit Retail Bank)", "THBBankDirect"},
	{"THB", "", "SMBC", "ธนาคารซูมิโตโม มิตซุย แบงกิ้ง คอร์ปอเรชั่น(Sumitomo Mitsui Bank)", "THBBankDirect"},
	{"THB", "", "SCBT", "ธนาคารสแตนดาร์ดชาร์เตอร์ด (ไทย)(Standard Chartered Bank (Thai))", "THBBankDirect"},
	{"THB", "SCB", "SCB", "ธนาคารไทยพาณิชย์(SCB Siam Commercial Bank Plc)", "THBBankDirect"},
	{"THB", "", "MHBK", "ธนาคารมิซูโฮ จำกัด สาขากรุงเทพฯ(Mizuho Bank, Ltd. Bangkok Branch)", "THBBankDirect"},
	{"THB", "", "MEGA ICBC", "ธนาคารเมกะ สากลพาณิชย์ จำกัด(Mega International Commercial Bank)", "THBBankDirect"},
	{"THB", "", "LH BANK", "ธนาคารแลนด์แอนด์เฮ้าส์(Land and Houses Bank)", "THBBankDirect"},
	{"THB", "KTB", "KTB", "ธนาคารกรุงไทย จำกัด (มหาชน) (KRUNG THAI BANK)", "THBBankDirect"},
	{"THB", "KKP", "KKP", "ธนาคารเกียรตินาคินภัทร จำกัด (มหาชน)(Kiatnakin Phatra Bank)", "THBBankDirect"},
	{"THB", "KBANK", "KBANK", "ธ.กสิกรไทย จำกัด(KASIKORNBANK Public Company Limited)", "THBBankDirect"},
	{"THB", "ISBT", "ISBT", "ธนาคารอิสลามแห่งประเทศไทย(Islamic Bank of Thailand)", "THBBankDirect"},
	{"THB", "", "IOBA", "ธนาคาร อินเดียน โอเวอร์ซีร์(INDIAN OVERSEAS BANK)", "THBBankDirect"},
	{"THB", "ICBCT", "ICBC", "ธนาคารไอซีบีซี (ไทย) จำกัด (มหาชน)(Industrial and Commercial Bank of China (Thai))", "THBBankDirect"},
	{"THB", "", "HSBC", "ธนาคารฮ่องกงและเซี่ยงไฮ้จำกัด(Hongkong and Shanghai Bank)", "THBBankDirect"},
	{"THB", "GSB", "GSB", "ธนาคารออมสิน(Government Savings Bank)", "THBBankDirect"},
	{"THB", "GHB", "GHB", "ธนาคารอาคารสงเคราะห์(Government Housing Bank)", "THBBankDirect"},
	{"THB", "", "DEUTSHE", "ธนาคารดอยซ์แบงค์(Deutsche Bank)", "THBBankDirect"},
	{"THB", "", "CITI", "ธนาคารซิตี้แบงก์(CITIBANK)", "THBBankDirect"},
	{"THB", "CIMBT", "CIMBT", "ธนาคารซีไอเอ็มบี จำกัด (มหาชน)(CIMB Thai Bank)", "THBBankDirect"},
	{"THB", "", "BOC", "ธนาคารแห่งประเทศจีน (ไทย) จำกัด (มหาชน)์(Bank of China (Thai))", "THBBankDirect"},
	{"THB", "", "BNPP", "ธนาคารบีเอ็นพี พารีบาส์(BNP Paribask)", "THBBankDirect"},
	{"THB", "BBL", "BBL", "ธนาคารกรุงเทพ(Bangkok Bank Public Company Limited)", "THBBankDirect"},
	{"THB", "BAY", "BAY", "ธนาคารกรุงศรีอยุธยา(Bank of Ayudhaya Public Company Limited)", "THBBankDirect"},
	{"THB", "BAAC", "BAAC", "ธนาคารเพื่อการเกษตรและสหกรณ์(Bank for Agriculture and Agricultural)", "THBBankDirect"},
	{"THB", "", "BA", "ธนาคารแห่งอเมริกา เนชั่นแนลฯ(Bank of America)", "THBBankDirect"},
	{"THB", "", "ANZ", "ธนาคารเอเอ็นแซด (ไทย)(ANZ Bank (Thai))", "THBBankDirect"},

	{"THB", "TISCO", "029", "ธนาคารทิสโก้ จำกัด (มหาชน)(Tisco Bank)", "TPBankDirect"},
	{"THB", "", "028", "ธนาคารอิสลามแห่งประเทศไทย(Islamic Bank of Thailand)", "TPBankDirect"},
	{"THB", "", "026", "ธนาคารเพื่อการเกษตรและสหกรณ์(Bank for Agriculture and Agricultural)", "TPBankDirect"},
	{"THB", "", "025", "ธนาคารอาคารสงเคราะห์(Government Housing Bank)", "TPBankDirect"},
	{"THB", "", "024", "ธนาคารซิตี้แบงก์(CITIBANK)", "TPBankDirect"},
	{"THB", "", "023", "ธนาคารเกียรตินาคินภัทร จำกัด (มหาชน)(Kiatnakin Phatra Bank)", "TPBankDirect"},
	{"THB", "", "022", "ธนาคารออมสิน(Government Savings Bank)", "TPBankDirect"},
	{"THB", "", "020", "ธนาคารแลนด์แอนด์เฮ้าส์(Land and Houses Bank)", "TPBankDirect"},
	{"THB", "", "018", "ธนาคารซีไอเอ็มบี จำกัด (มหาชน)(CIMB Thai Bank)", "TPBankDirect"},
	{"THB", "", "017", "ธนาคารกรุงศรีอยุธยา(Bank of Ayudhaya Public Company Limited)", "TPBankDirect"},
	{"THB", "", "016", "ธนาคารยูโอบี จำกัด (มหาชน)(United Overseas Bank (Thai))", "TPBankDirect"},
	{"THB", "", "010", "ธนาคารไทยพาณิชย์(SCB Siam Commercial Bank Plc)", "TPBankDirect"},
	{"THB", "", "007", "ธนาคารทหารไทย(TMBThanachart Bank Public Company Limited)", "TPBankDirect"},
	{"THB", "", "005", "ธนาคารเอแบีเอ็น แอมโร จำกัด (ABN AMRO BANK)", "TPBankDirect"},
	{"THB", "", "004", "ธนาคารกรุงไทย จำกัด (มหาชน) (KRUNG THAI BANK)", "TPBankDirect"},
	{"THB", "", "003", "ธนาคารกรุงเทพ(Bangkok Bank Public Company Limited)", "TPBankDirect"},
	{"THB", "", "001", "ธ.กสิกรไทย จำกัด(KASIKORNBANK Public Company Limited)", "TPBankDirect"},

	{"IDR", "MUTI", "10010", "Bank MUTIARA", "JYBankDirect"},
	{"IDR", "", "10009", "LINKAJA", "JYBankDirect"},
	{"IDR", "", "10008", "SHOPEEPAY", "JYBankDirect"},
	{"IDR", "", "10006", "Bank MULTICOR", "JYBankDirect"},
	{"IDR", "", "501", "Royal Bank of Scotland (RBS)", "JYBankDirect"},
	{"IDR", "BMAN", "5640", "Bank Mandiri Taspen Pos", "JYBankDirect"},
	{"IDR", "", "032", "JPMORGAN CHASE BANK", "JYBankDirect"},
	{"IDR", "DBAG", "067", "Deutsche Bank", "JYBankDirect"},
	{"IDR", "", "088", "CCB Indonesia", "JYBankDirect"},
	{"IDR", "", "5590", "Bank Centratama", "JYBankDirect"},
	{"IDR", "BPYO", "1120", "BPD_Daerah_Istimewa_Yogyakarta_(DIY)", "JYBankDirect"},
	{"IDR", "", "490", "Neo Commerce/Bank Yudha Bhakti(BNC)", "JYBankDirect"},
	{"IDR", "SAUD", "212", "Bank Woori Saudara", "JYBankDirect"},
	{"IDR", "", "405", "Bank Victoria Syariah", "JYBankDirect"},
	{"IDR", "", "566", "Bank Victoria International", "JYBankDirect"},
	{"IDR", "", "023", "TMRW/Bank UOB Indonesia", "JYBankDirect"},
	{"IDR", "", "042", "Bank of Tokyo", "JYBankDirect"},
	{"IDR", "BSMA", "451", "Bank Syariah Mandiri(BSM)", "JYBankDirect"},
	{"IDR", "", "045", "Bank Sumitomo Mitsui Indonesia", "JYBankDirect"},
	{"IDR", "SAUD", "1530", "Bank Sinarmas UUS", "JYBankDirect"},
	{"IDR", "", "1170", "Bank Sumut UUS", "JYBankDirect"},
	{"IDR", "SUMU", "117", "Bank Sumut", "JYBankDirect"},
	{"IDR", "", "1200", "Bank Sumsel Babel UUS", "JYBankDirect"},
	{"IDR", "", "120", "BPD Sumsel Babel", "JYBankDirect"},
	{"IDR", "", "1180", "BPD Sumatera Barat UUS", "JYBankDirect"},
	{"IDR", "", "118", "BPD Sumatera Barat", "JYBankDirect"},
	{"IDR", "BPSU", "127", "BPD Sulawesi Utara(SulutGo)", "JYBankDirect"},
	{"IDR", "", "1260", "Bank Sulselbar UUS", "JYBankDirect"},
	{"IDR", "", "126", "Bank Sulselbar", "JYBankDirect"},
	{"IDR", "", "135", "Bank Sultra", "JYBankDirect"},
	{"IDR", "", "134", "Bank Sulteng", "JYBankDirect"},
	{"IDR", "BSC", "050", "Standard Chartered Bank", "JYBankDirect"},
	{"IDR", "BSI", "153", "Bank Sinarmas", "JYBankDirect"},
	{"IDR", "", "152", "Bank Shinhan Indonesia", "JYBankDirect"},
	{"IDR", "", "498", "Bank SBI Indonesia", "JYBankDirect"},
	{"IDR", "", "523", "Bank Sahabat Sampoerna", "JYBankDirect"},
	{"IDR", "BPRI", "1190", "BPD Riau Dan Kepri UUS", "JYBankDirect"},
	{"IDR", "BPRI", "119", "BPD Riau Dan Kepri", "JYBankDirect"},
	{"IDR", "", "047", "Bank Resona Perdania", "JYBankDirect"},
	{"IDR", "RABO", "089", "Rabobank International Indonesia", "JYBankDirect"},
	{"IDR", "", "5260", "Bank Oke Indonesia", "JYBankDirect"},
	{"IDR", "", "1670", "QNB Indonesia", "JYBankDirect"},
	{"IDR", "QNBK", "167", "QNB KESAWAN", "JYBankDirect"},
	{"IDR", "", "520", "Bank Prima Master", "JYBankDirect"},
	{"IDR", "", "0130", "Bank Permata UUS", "JYBankDirect"},
	{"IDR", "BP", "013", "Bank Permata", "JYBankDirect"},
	{"IDR", "", "132", "Bank Papua", "JYBankDirect"},
	{"IDR", "", "517", "Panin Dubai Syariah", "JYBankDirect"},
	{"IDR", "PANIN", "019", "Bank Panin", "JYBankDirect"},
	{"IDR", "BON", "0280", "Bank OCBC NISP UUS", "JYBankDirect"},
	{"IDR", "BON", "028", "Bank OCBC NISP", "JYBankDirect"},
	{"IDR", "", "145", "Bank Nusantara Parahyangan", "JYBankDirect"},
	{"IDR", "NTT", "130", "BPD Nusa Tenggara Timur(NTT)", "JYBankDirect"},
	{"IDR", "BNTB", "1280", "BPD Nusa Tenggara Barat (NTB) UUS", "JYBankDirect"},
	{"IDR", "BNTB", "128", "BPD Nusa Tenggara Barat(NTB)", "JYBankDirect"},
	{"IDR", "BNN", "503", "Bank National Nobu", "JYBankDirect"},
	{"IDR", "", "048", "Bank Mizuho Indonesia", "JYBankDirect"},
	{"IDR", "", "491", "Bank Mitra Niaga", "JYBankDirect"},
	{"IDR", "BMU", "147", "Bank Muamalat Indonesia", "JYBankDirect"},
	{"IDR", "", "485", "Motion/Bank MNC Internasional", "JYBankDirect"},
	{"IDR", "", "151", "Bank Mestika Dharma", "JYBankDirect"},
	{"IDR", "BSME", "506", "Bank Mega Syariah", "JYBankDirect"},
	{"IDR", "BMEG", "426", "Bank Mega", "JYBankDirect"},
	{"IDR", "MAYO", "553", "Bank Mayora Indonesia", "JYBankDirect"},
	{"IDR", "BSID", "947", "Bank Maybank Syariah Indonesia", "JYBankDirect"},
	{"IDR", "", "016", "Bank Maybank", "JYBankDirect"},
	{"IDR", "BMI", "097", "Bank Mayapada", "JYBankDirect"},
	{"IDR", "", "157", "Bank Maspion Indonesia", "JYBankDirect"},
	{"IDR", "", "548", "Bank Multi Arta Sentosa(MAS)", "JYBankDirect"},
	{"IDR", "", "564", "Bank MANTAP", "JYBankDirect"},
	{"IDR", "", "008", "Bank Mandiri", "JYBankDirect"},
	{"IDR", "", "131", "Bank Maluku", "JYBankDirect"},
	{"IDR", "BPLA", "121", "BPD Lampung", "JYBankDirect"},
	{"IDR", "", "535", "Seabank/Bank Kesejahteraan Ekonomi(BKE)", "JYBankDirect"},
	{"IDR", "BPKT", "1240", "BPD Kalimantan Timur UUS", "JYBankDirect"},
	{"IDR", "BPKT", "124", "BPD Kalimantan Timur", "JYBankDirect"},
	{"IDR", "", "125", "BPD Kalimantan Tengah (Kalteng)", "JYBankDirect"},
	{"IDR", "", "1220", "BPD Kalimantan Selatan UUS", "JYBankDirect"},
	{"IDR", "", "122", "BPD Kalimantan Selatan/Kalsel", "JYBankDirect"},
	{"IDR", "BPKB", "1230", "BPD Kalimantan Barat UUS", "JYBankDirect"},
	{"IDR", "BPKB", "123", "BPD Kalimantan Barat/Kalbar", "JYBankDirect"},
	{"IDR", "", "095", "Bank JTrust Indonesia", "JYBankDirect"},
	{"IDR", "BJ", "114", "Bank Jatim", "JYBankDirect"},
	{"IDR", "", "113", "Bank Jateng", "JYBankDirect"},
	{"IDR", "", "472", "Bank Jasa Jakarta", "JYBankDirect"},
	{"IDR", "", "115", "Bank Jambi", "JYBankDirect"},
	{"IDR", "", "146", "Bank of India Indonesia", "JYBankDirect"},
	{"IDR", "", "555", "Bank Index Selindo", "JYBankDirect"},
	{"IDR", "", "513", "Bank Ina Perdana", "JYBankDirect"},
	{"IDR", "", "164", "Bank ICBC Indonesia", "JYBankDirect"},
	{"IDR", "HSBC", "041", "HSBC", "JYBankDirect"},
	{"IDR", "", "2120", "Bank Himpunan Saudara 1906", "JYBankDirect"},
	{"IDR", "", "567", "Allo Bank/Bank Harda Internasional", "JYBankDirect"},
	{"IDR", "HANA", "484", "LINE Bank/KEB Hana", "JYBankDirect"},
	{"IDR", "", "161", "Bank Ganesha", "JYBankDirect"},
	{"IDR", "", "699", "Bank EKA", "JYBankDirect"},
	{"IDR", "", "562", "Bank Fama International", "JYBankDirect"},
	{"IDR", "", "778", "Bank DKI UUS", "JYBankDirect"},
	{"IDR", "", "111", "Bank DKI", "JYBankDirect"},
	{"IDR", "", "526", "Bank Dinar Indonesia", "JYBankDirect"},
	{"IDR", "DBS", "046", "Bank DBS Indonesia", "JYBankDirect"},
	{"IDR", "", "0110", "Bank Danamon UUS", "JYBankDirect"},
	{"IDR", "", "011", "Bank Danamon", "JYBankDirect"},
	{"IDR", "", "112", "BPD DIY", "JYBankDirect"},
	{"IDR", "BCOM", "950", "Bank Commonwealth", "JYBankDirect"},
	{"IDR", "CITI", "031", "Citibank", "JYBankDirect"},
	{"IDR", "", "0220", "Bank CIMB Niaga UUS", "JYBankDirect"},
	{"IDR", "CIMB", "022", "Bank CIMB Niaga", "JYBankDirect"},
	{"IDR", "", "559", "Centratama Nasional Bank(CNB)", "JYBankDirect"},
	{"IDR", "CTBC", "949", "CTBC Indonesia", "JYBankDirect"},
	{"IDR", "", "054", "Bank Capital Indonesia", "JYBankDirect"},
	{"IDR", "", "076", "Bank Bumi Arta", "JYBankDirect"},
	{"IDR", "BBUK", "521", "Bank Bukopin Syariah", "JYBankDirect"},
	{"IDR", "", "441", "Wokee/Bukopin", "JYBankDirect"},
	{"IDR", "", "547", "Bank BTPN Syariah", "JYBankDirect"},
	{"IDR", "", "5470", "BTPN Syariah", "JYBankDirect"},
	{"IDR", "BTPN", "213", "Bank BTPN", "JYBankDirect"},
	{"IDR", "", "2000", "Bank Tabungan Negara (BTN) UUS", "JYBankDirect"},
	{"IDR", "", "200", "Bank Tabungan Negara (BTN)", "JYBankDirect"},
	{"IDR", "", "4510", "Bank Syariah Indonesia(BSI)", "JYBankDirect"},
	{"IDR", "", "1450", "Bank BNP Paribas", "JYBankDirect"},
	{"IDR", "BBS", "422", "Bank BRI Syariah", "JYBankDirect"},
	{"IDR", "BRI", "002", "Bank Rakyat Indonesia(BRI)", "JYBankDirect"},
	{"IDR", "", "069", "BANK OF CHINA LIMITED", "JYBankDirect"},
	{"IDR", "BBNS", "427", "Bank BNI Syariah", "JYBankDirect"},
	{"IDR", "", "009", "Bank Negara Indonesia(BNI)", "JYBankDirect"},
	{"IDR", "BJB_SYR", "425", "Bank BJB Syariah", "JYBankDirect"},
	{"IDR", "", "110", "Bank Jawa Barat(BJB)", "JYBankDirect"},
	{"IDR", "", "133", "Bank Bengkulu", "JYBankDirect"},
	{"IDR", "BCA", "536", "Bank Central Asia (BCA) Syariah", "JYBankDirect"},
	{"IDR", "", "014", "Bank Central Asia(BCA)", "JYBankDirect"},
	{"IDR", "", "558", "BPD Banten", "JYBankDirect"},
	{"IDR", "", "040", "Bangkok Bank", "JYBankDirect"},
	{"IDR", "", "459", "Bank Bisnis Internasional", "JYBankDirect"},
	{"IDR", "BPD", "129", "BPD Bali", "JYBankDirect"},
	{"IDR", "", "542", "Bank ARTOS/ Bank Jago", "JYBankDirect"},
	{"IDR", "", "037", "Bank Artha Graha Internasional", "JYBankDirect"},
	{"IDR", "", "020", "Bank Arta Niaga Kencana", "JYBankDirect"},
	{"IDR", "", "061", "Bank ANZ Indonesia", "JYBankDirect"},
	{"IDR", "", "531", "Anglomas International Bank", "JYBankDirect"},
	{"IDR", "", "466", "Bank Andara", "JYBankDirect"},
	{"IDR", "", "494", "Bank Agroniaga", "JYBankDirect"},
	{"IDR", "", "945", "Bank IBK Indonesia", "JYBankDirect"},
	{"IDR", "", "1160", "Bank Agris UUS", "JYBankDirect"},
	{"IDR", "", "116", "Bank Aceh Syariah", "JYBankDirect"},
	{"IDR", "", "10003", "GOPAY", "JYEwallet"},
	{"IDR", "", "10002", "DANA", "JYEwallet"},
	{"IDR", "", "10001", "OVO", "JYEwallet"},

	{"PHP", "ZT", "ZT", "Zybi Tech Inc.", "SpDfBank"},
	{"PHP", "WPI", "WPI", "Wise Pilipinas, Inc.", "SpDfBank"},
	{"PHP", "WDB", "WDB", "Wealth Development Bank Corporation", "SpDfBank"},
	{"PHP", "USSCMONEY", "USSCMONEY", "USSC Money Services, Inc", "SpDfBank"},
	{"PHP", "UNOB", "UNOB", "UnoBank Inc.", "SpDfBank"},
	{"PHP", "UCBPH", "UCBPH", "United Coconut Planters Bank", "SpDfBank"},
	{"PHP", "UBSB", "UBSB", "Union Digital Bank", "SpDfBank"},
	{"PHP", "UCPBSB", "UCPBSB", "UCPB Savings Bank,Inc.", "SpDfBank"},
	{"PHP", "TP", "TP", "Traxion Pay Inc.", "SpDfBank"},
	{"PHP", "TJT", "TJT", "Topjuan Tech Corporation", "SpDfBank"},
	{"PHP", "TDB", "TDB", "Tonik Digital Bank", "SpDfBank"},
	{"PHP", "TTWI", "TTWI", "TokTok Wallet Inc.", "SpDfBank"},
	{"PHP", "TCI", "TCI", "Tayocash Inc.", "SpDfBank"},
	{"PHP", "SSB", "SSB", "Sun Savings Bank,Inc.", "SpDfBank"},
	{"PHP", "SBAA", "SBAA", "Sterling Bank of Asia, Inc.,A Savings Bank", "SpDfBank"},
	{"PHP", "STARP", "STARP", "Starpay Corporation", "SpDfBank"},
	{"PHP", "SCB", "SCB", "Standard Chartered Bank", "SpDfBank"},
	{"PHP", "SPEEDYPAY", "SPEEDYPAY", "SpeedyPay Inc.", "SpDfBank"},
	{"PHP", "ShopeePay", "ShopeePay", "ShopeePay Philippines,Inc.", "SpDfBank"},
	{"PHP", "SBC2", "SBC2", "Security Bank Corporation 2", "SpDfBank"},
	{"PHP", "SBP", "SBP", "Seabank Philippines,Inc.", "SpDfBank"},
	{"PHP", "RBRB", "RBRB", "Rural Bank of Guinobatan,Inc.", "SpDfBank"},
	{"PHP", "RBGP", "RBGP", "Robinsons Bank Corporation", "SpDfBank"},
	{"PHP", "RANG_AY_BANK", "RANG_AY_BANK", "RANG-AY BANK A Rural Bank Inc", "SpDfBank"},
	{"PHP", "QCRB", "QCRB", "Quezon Capital Rural Bank,Inc.", "SpDfBank"},
	{"PHP", "QCBDB", "QCBDB", "Queen City Development Bank,Inc.", "SpDfBank"},
	{"PHP", "PSBC", "PSBC", "Producers Savings Bank Corporation", "SpDfBank"},
	{"PHP", "PPSPEPP", "PPSPEPP", "PPS-PEPP Financial Services Corporation", "SpDfBank"},
	{"PHP", "PHTB", "PHTB", "PhilTrust Bank", "SpDfBank"},
	{"PHP", "PVB", "PVB", "Philippine Veterans Bank", "SpDfBank"},
	{"PHP", "PSB", "PSB", "Philippine Savings Bank", "SpDfBank"},
	{"PHP", "PDAE", "PDAE", "Philippine Digital Asset Exchange", "SpDfBank"},
	{"PHP", "PBB", "PBB", "Philippine Business Bank", "SpDfBank"},
	{"PHP", "PBC", "PBC", "Philippine Bank of Communications", "SpDfBank"},
	{"PHP", "PRBRB", "PRBRB", "Partner Rural Bank (Cotabato),Inc.", "SpDfBank"},
	{"PHP", "PASB", "PASB", "Pacific Ace Savings Bank,Inc.", "SpDfBank"},
	{"PHP", "OWNB", "OWNB", "OWN BANK THE RURAL BANK OF CAVITE CITY INC.", "SpDfBank"},
	{"PHP", "MCB", "MCB", "Mindanao Consolidated Cooperative Bank", "SpDfBank"},
	{"PHP", "MAYBANK_PH", "MAYBANK_PH", "Maybank Philippines,Inc.", "SpDfBank"},
	{"PHP", "MAYABANK", "MAYABANK", "MAYA BANK,INC", "SpDfBank"},
	{"PHP", "MBSM", "MBSM", "Malayan Bank Savings and Mortgage Bank,Inc.", "SpDfBank"},
	{"PHP", "LDB", "LDB", "Luzon Development Bank", "SpDfBank"},
	{"PHP", "LFS", "LFS", "Lulu Financial Services", "SpDfBank"},
	{"PHP", "LSB", "LSB", "Legazpi Savings Bank", "SpDfBank"},
	{"PHP", "ISLAB", "ISLAB", "ISLA Bank (A Thrift Bank),Inc.", "SpDfBank"},
	{"PHP", "IREMIT", "IREMIT", "I-Remit Inc.", "SpDfBank"},
	{"PHP", "ING", "ING", "ING Bank N.V.", "SpDfBank"},
	{"PHP", "INFOSERVE", "INFOSERVE", "INFOSERVE INCORPORATED", "SpDfBank"},
	{"PHP", "HKBSPH", "HKBSPH", "The Hong Kong and Shanghai Banking Corporation Limited, Philippine Branch", "SpDfBank"},
	{"PHP", "GTB", "GTB", "GoTyme Bank Corporation", "SpDfBank"},
	{"PHP", "ESB", "ESB", "Equicom Savings Bank,Inc.", "SpDfBank"},
	{"PHP", "EPGEMI", "EPGEMI", "Easy Pay Global EMI Corp", "SpDfBank"},
	{"PHP", "EWC", "EWC", "East West Banking Corporation", "SpDfBank"},
	{"PHP", "DGB", "DGB", "Dungganon Bank (A Microfinance Rural Bank),Inc.", "SpDfBank"},
	{"PHP", "DCDPH", "DCDPH", "Dumaguete City Development Bank", "SpDfBank"},
	{"PHP", "CTBC", "CTBC", "CTBC Bank (Philippines) Corporation", "SpDfBank"},
	{"PHP", "CRBRB", "CRBRB", "Community Rural Bank of Romblon,Inc.", "SpDfBank"},
	{"PHP", "CIS", "CIS", "CIS Bayad Center,Inc.", "SpDfBank"},
	{"PHP", "CIMB", "CIMB", "CIMB Philippines,Inc.", "SpDfBank"},
	{"PHP", "CBPH", "CBPH", "China Bank Savings,Inc.", "SpDfBank"},
	{"PHP", "CLRB", "CLRB", "Cebuana Lhuillier Rural Bank,Inc", "SpDfBank"},
	{"PHP", "CSMB", "CSMB", "CARD SME Bank,Inc.A Thrift Bank", "SpDfBank"},
	{"PHP", "CARD_BANK", "CARD_BANK", "CARD BANK Inc.", "SpDfBank"},
	{"PHP", "CANTILAN_BANK", "CANTILAN_BANK", "Cantilan Bank Inc.", "SpDfBank"},
	{"PHP", "CBRB", "CBRB", "Camalig Bank, Inc. (A Rural Bank)", "SpDfBank"},
	{"PHP", "BPIDB", "BPIDB", "BPI Direct BanKo", "SpDfBank"},
	{"PHP", "BDB", "BDB", "BDO Network Bank", "SpDfBank"},
	{"PHP", "BBI", "BBI", "Bayanihan Bank Inc.", "SpDfBank"},
	{"PHP", "BOCOMMERCE", "BOCOMMERCE", "Bank of Commerce", "SpDfBank"},
	{"PHP", "BOCHINA", "BOCHINA", "Bank of China", "SpDfBank"},
	{"PHP", "BMAB", "BMAB", "Bangko Mabuhay (A Rural Bank), Inc.", "SpDfBank"},
	{"PHP", "BFS", "BFS", "Bananapay Fintech Services", "SpDfBank"},
	{"PHP", "AUBC", "AUBC", "Asia United Bank Corporation", "SpDfBank"},
	{"PHP", "ABTB", "ABTB", "AllBank (A Thrift Bank), Inc.", "SpDfBank"},
	{"PHP", "APH", "APH", "Alipay Philippines", "SpDfBank"},
	{"PHP", "PNB", "PNB", "Philippine National Bank", "SpDfBank"},
	{"PHP", "RCBC", "RCBC", "Rizal Commercial Banking Corporation", "SpDfBank"},
	{"PHP", "DBPH", "DBPH", "Development Bank of the Philippines", "SpDfBank"},
	{"PHP", "CBC", "CBC", "China Banking Corporation", "SpDfBank"},
	{"PHP", "SBC", "SBC", "Security Bank Corporation", "SpDfBank"},
	{"PHP", "LBPH", "LBPH", "Land Bank of the Philippines", "SpDfBank"},
	{"PHP", "BPIF", "BPIF", "Bank of the Philippine Islands / BPI Family", "SpDfBank"},
	{"PHP", "MBTC", "MBTC", "Metropolitan Bank and Trust Company", "SpDfBank"},
	{"PHP", "BDO", "BDO", "BDO Unibank,Inc.", "SpDfBank"},
	{"PHP", "UBPH", "UBPH", "Union Bank of the Philippines", "SpDfBank"},
	{"PHP", "COINS", "COINS", "coins.ph", "SpDfBank"},
	{"PHP", "GRABPAY", "GRABPAY", "grabpay", "SpDfBank"},
	{"PHP", "OMNIPAY", "OMNIPAY", "omnipay", "SpDfBank"},
	{"PHP", "MAYA", "MAYA", "maya", "SpDfBank"},
	{"PHP", "GCASH", "GCASH", "gcash", "SpDfBank"},
}
